; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28019.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\gigabyte\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
